

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "firstname": "Liam",
    "lastname": "ENgel",
    "gender": "Male",
    "userRole": "user",
    "email": "engelliam71@gmaill.com",
    "userpassword": "liam2022",
}