GET http://localhost:3000/products

###
POST https://liam-picknpayapi.herokuapp.com/register
Content-Type: application/json

{
    "firstname": "Peter",
    "lastname": "Peterson",
    "gender": "Male",
    
}