

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "firstname": "Peter",
    "lastname": "Peterson",
    "gender": "Male",
    "userRole": "user",
    "email": "peter@gmaill.com",
    "userpassword": "peter2022"
}